services:
  mysql:
    image: mysql:8.4
    container_name: mineria-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mineria_mysql
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:17
    container_name: mineria-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mineria_pg
      POSTGRES_USER: alumno
      POSTGRES_PASSWORD: alumno123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data: